
<!-- SLIDER BOF -->
<?php if (($_products = $this->getLatestCollection()) && $_products->getSize()): ?>
<div class="slider-container">
<div class="clearfix">
	<h2 class="subtitle"><?php echo $this->__('Sản phẩm nổi bật') ?></h2>
	 
</div>
<div class="home-pro">
    <ul class="products-grid">
    <?php foreach ($_products->getItems() as $_product): ?>
        <li  class="item">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                <?php echo $this->helper('celebritysettings')->getLabel($_product);  ?>
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220, 330) ?>" width="220" height="330" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /><em><?php echo $this->__('Details'); ?></em><span></span></a>
            <div class="info">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
</div>

<?php endif; ?>
<!-- SLIDER EOF -->
